### PR TITLE
Reflect current branding for Anaconda - no more CE

### PR DESCRIPTION
**Pull request by deeplycloudy**
Per http://continuum.io/blog/anaconda-1-4-released, and the redirect behavior at the old URL. Should help eliminate some confusion when students ask, "where's CE?"

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Have you let Greg know to update the default? Seems important.

**Comment by deeplycloudy** [comment]
Nope, would he prefer an email or a PR? Saw he forked your TTU repo; would that be the best place for a pull?

**Comment by wrightaprilm** [comment]
I think he'd prefer a PR. The repo from which mine was forked is here: https://github.com/swcarpentry/bc, and the setup.html file that all SWC instructors are using is in the _includes folder. I think that's where to make your PR so it's there for all the different bootcamps that happen throughout the year.

**Comment by deeplycloudy** [comment]
Just filed against the upstream source - thanks for the navigation instructions.

**Pull request merged**
